=== everton137/leavex.eu/schemas/mp.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "name",
      "country",
      "countryCode",
      "level",
      "institution",
      "role",
      "party",
      "email",
      "usesX",
      "xHandle"
    ],
    "properties": {
      "id": {
        "type": "string",
        "description": "Unique identifier for the representative"
      },
      "name": {
        "type": "string",
        "description": "Full name of the representative"
      },
      "country": {
        "type": "string",
        "description": "Country the representative represents"
      },
      "countryCode": {
        "type": "string",
        "pattern": "^[A-Z]{2}$",
        "description": "ISO 3166-1 alpha-2 country code"
      },
      "level": {
        "type": "string",
        "enum": ["eu", "national"],
        "description": "Level of government (EU or national)"
      },
      "institution": {
        "type": "string",
        "description": "Name of the institution or parliament"
      },
      "role": {
        "type": "string",
        "description": "Role or position (e.g., MEP, MP)"
      },
      "party": {
        "type": "string",
        "description": "Political party or group affiliation"
      },
      "euGroupFull": {
        "type": "string",
        "description": "Full name political party in European parlement"
      },
      "email": {
        "type": ["string", "null"],
        "format": "email",
        "description": "Official email address"
      },
      "usesX": {
        "type": "boolean",
        "description": "A politician is considered \"active on X\" if they have an account and there is no public statement indicating that they have left the platform. This applies even if the account has not posted recently."
      },
      "xHandle": {
        "type": ["string", "null"],
        "pattern": "^@[a-zA-Z0-9_]+$|^$",
        "description": "X (Twitter) handle, including @ symbol, or null if not applicable"
      },
      "xStatus": {
        "enum": ["exited", "active"],
        "description": "Status on X"
      },
      "xLeftAt": {
        "type": ["string", "null"],
        "format": "date",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
        "description": "Date the person left X"
      },
      "xNotes": {
        "type": "string",
        "description": "Exit message on X"
      },
      "xLastArchiveUrl": {
        "type": "string",
        "format": "url",
        "description": "Internet archive URL of last message on X"
      },
      "source": {
        "enum": ["manual", "automatic"],
        "description": "Source of X status"
      },
      "updatedAt": {
        "type": "string",
        "format": "date",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
        "description": "Date of the latest update"
      }
    },
    "additionalProperties": false
  }
}

=== everton137/leavex.eu/data/politicians/at/mps.json
[ {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : false,
  "email" : "lisa.aldali@parlament.gv.at",
  "xHandle" : null,
  "name" : "Lisa Aldali",
  "level" : "national",
  "id" : "at_nr_38385",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : true,
  "email" : null,
  "xHandle" : "@auer_katrin",
  "name" : "Mag. Katrin Auer",
  "level" : "national",
  "id" : "at_nr_30688",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : false,
  "email" : "gertraud.auinger-oberzaucher@parlament.gv.at",
  "xHandle" : null,
  "name" : "Mag. Gertraud Auinger-Oberzaucher",
  "level" : "national",
  "id" : "at_nr_30668",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Roland Baumann",
  "level" : "national",
  "id" : "at_nr_30689",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "angela.baumgartner@parlament.gv.at",
  "xHandle" : null,
  "name" : "Angela Baumgartner",
  "level" : "national",
  "id" : "at_nr_1974",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : true,
  "email" : "petra.bayr@parlament.gv.at",
  "xHandle" : "@BayrPetra",
  "name" : "Petra Bayr, MA MLS",
  "level" : "national",
  "id" : "at_nr_14835",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : "dagmar.belakowitsch@parlament.gv.at",
  "xHandle" : null,
  "name" : "Dr. Dagmar Belakowitsch",
  "level" : "national",
  "id" : "at_nr_35468",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : "ricarda.berger@parlament.gv.at",
  "xHandle" : null,
  "name" : "Ricarda Berger",
  "level" : "national",
  "id" : "at_nr_2996",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Tina Angela Berger",
  "level" : "national",
  "id" : "at_nr_30645",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : false,
  "email" : "michael.bernhard@parlament.gv.at",
  "xHandle" : null,
  "name" : "Michael Bernhard",
  "level" : "national",
  "id" : "at_nr_83124",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : true,
  "email" : null,
  "xHandle" : "@Reini_Binder",
  "name" : "Reinhold Binder",
  "level" : "national",
  "id" : "at_nr_30693",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "juliane.bogner-strauss@parlament.gv.at",
  "xHandle" : null,
  "name" : "Mag. Dr. Juliane Bogner-Strauß",
  "level" : "national",
  "id" : "at_nr_1975",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : true,
  "email" : "henrike.brandstoetter@parlament.gv.at",
  "xHandle" : "@brand_rede",
  "name" : "Henrike Brandstötter",
  "level" : "national",
  "id" : "at_nr_5683",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "lukas.brandweiner@parlament.gv.at",
  "xHandle" : null,
  "name" : "Lukas Brandweiner",
  "level" : "national",
  "id" : "at_nr_5438",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Hermann Brückl, MA",
  "level" : "national",
  "id" : "at_nr_61639",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "Unknown",
  "usesX" : false,
  "email" : "doris.bures@parlament.gv.at",
  "xHandle" : null,
  "name" : "Doris Bures",
  "level" : "national",
  "id" : "at_nr_145",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Mag. Gernot Darmann",
  "level" : "national",
  "id" : "at_nr_35469",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Mag. Romana Deckenbacher",
  "level" : "national",
  "id" : "at_nr_6506",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : "gerhard.deimek@fpoe.at",
  "xHandle" : null,
  "name" : "Dipl.-Ing. Gerhard Deimek",
  "level" : "national",
  "id" : "at_nr_51557",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Mag. Antonio Della Rossa",
  "level" : "national",
  "id" : "at_nr_30694",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Veit Valentin Dengler",
  "level" : "national",
  "id" : "at_nr_30669",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "martina.diesner-wais@parlament.gv.at",
  "xHandle" : null,
  "name" : "Martina Diesner-Wais",
  "level" : "national",
  "id" : "at_nr_16218",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "GRÜNE",
  "usesX" : true,
  "email" : "meri.disoski@gruene.at",
  "xHandle" : "@disoski",
  "name" : "Mag. Meri Disoski",
  "level" : "national",
  "id" : "at_nr_5650",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : true,
  "email" : "karin.doppelbauer@parlament.gv.at",
  "xHandle" : "@doppelbauerk",
  "name" : "Dipl.-Ing. Karin Doppelbauer",
  "level" : "national",
  "id" : "at_nr_91141",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : false,
  "email" : "muna.duzdar@parlament.gv.at",
  "xHandle" : null,
  "name" : "Mag. Muna Duzdar",
  "level" : "national",
  "id" : "at_nr_60446",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Rosa Ecker, MBA",
  "level" : "national",
  "id" : "at_nr_87002",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "heike.eder@parlament.gv.at",
  "xHandle" : null,
  "name" : "Heike Eder, BSc MBA",
  "level" : "national",
  "id" : "at_nr_6151",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Mag. (FH) Kurt Egger",
  "level" : "national",
  "id" : "at_nr_20056",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Irene Eisenhut",
  "level" : "national",
  "id" : "at_nr_30646",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Ing. Thomas Elian",
  "level" : "national",
  "id" : "at_nr_32569",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : false,
  "email" : "melanie.erasim@parlament.gv.at",
  "xHandle" : null,
  "name" : "Melanie Erasim, MSc",
  "level" : "national",
  "id" : "at_nr_30653",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "Margreth Falkner",
  "level" : "national",
  "id" : "at_nr_30717",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "SPÖ",
  "usesX" : false,
  "email" : "elisabeth.feichtinger@parlament.gv.at",
  "xHandle" : null,
  "name" : "Elisabeth Feichtinger, BEd BEd",
  "level" : "national",
  "id" : "at_nr_2189",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "NEOS",
  "usesX" : false,
  "email" : "fiona.fiedler@parlament.gv.at",
  "xHandle" : null,
  "name" : "Fiona Fiedler, BEd",
  "level" : "national",
  "id" : "at_nr_5684",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "FPÖ",
  "usesX" : false,
  "email" : null,
  "xHandle" : null,
  "name" : "MMag. DDr. Hubert Fuchs",
  "level" : "national",
  "id" : "at_nr_83127",
  "country" : "Austria",
  "countryCode" : "AT"
}, {
  "institution" : "Nationalrat",
  "role" : "MP",
  "party" : "ÖVP",
  "usesX" : false,
  "email" : "klaus.fuerlinger@parlament.gv.at",
  "xHandle" : null,
  "name" : "Mag. Klaus Fürlinger",
